### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by dbuggz** [ElektorLabs/esp32-energymeter#1]
just reading through your code it looks like a typing error in src/ESPHome/esp32-energymeter.yaml, line 67-68. Do you mean ct2Amps? Also need to change line 83.

      current:
        name: "CT2 Current"
        id: ct3Amps

line 82-83
      current:
        name: " CT3 Current"
        id: ct2Amps

Regards
Dave

**Comment by Saad-Imtiaz** [comment]
Hi Dave,

Yes,I believe it is, thanks for pointing it out.

Regards,
Saad
