### ISSUE TITLE
STL / Reset

### ISSUE THREAD

**Issue by JmanNZ** [ElektorLabs/esp32-energymeter#3]
Hi
Could you please post the STL file the case.
I noticed that the ESP32S3 does not reset sometimes on powerup, Removing C18 has completely solved the issue for me.

Thanks again from me and my Home Assistant :)

**Comment by elektor-labs** [comment]
Hi @JmanNZ 

Thank you for the feedback!

I've added the STL files for the enclosure to the repository. You can find them here:
```hardware/KiCAD/esp32-energymeter-V2/enclosure```

Tip: For best results, consider printing it with PETG filament.

I'm really glad you enjoyed the project! 😊
